app.environment.name=prod
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secret-key=3cfa76ef14417c1c0ea51912fc056a80fcd04a7420f8e8bcd0a7717c272e007b
security.jwt.expiration-time=3600000
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}