spring.application.name=spring-boot-project
server.port = 8081
spring.profiles.active=dev
app.settings.ip=127.0.0.1
security.jwt.secret-key=3cfa76ef14417c1c0ea51912fc057a80fcd04a7420f8e8bcd0a7717c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000