app.environment.name=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_data_jpa
spring.datasource.username=postgres
spring.datasource.password=postgres2995
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=3cfa76ef14417c1c0ea51912fc057a80fcd04a7420f8e8bcd0a7717c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000

app.cors.allowed-origins=http://localhost:4200